config/routes.rb
Rails.application.routes.draw do
  root "cocktails#index"
  resources :cocktails, only:[:index, :show, :new, :create] do
    resources :doses, only:[:new, :create]
  end
  resources :doses, only:[:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  private

  def cocktails_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only:[:create, :new]

  def new
    @dose = Dose.new
  end

  def create
    @dose = @cocktail.doses.new(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<h1>Mister Cock/Tail</h1>
<%= link_to "Register a cocktail", new_cocktail_path %>
<div class="container">
  <% @cocktails.each do |cocktail| %>
    <div class="card" style="width: 18rem"> <%= link_to cocktail.name, cocktail_path(cocktail)%> </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<h2>Mister, do you have any Cock? Tail?</h2>
<%= render 'form' %>
<%= link_to "Back to homepage", cocktails_path %>

app/views/cocktails/show.html.erb
<h1> <%= @cocktail.name %> </h1>
 <% @cocktail.doses.each do |dose| %>
  <h3>
    <%= dose.ingredient.name %>
    <%= dose.description %>
  </h3>
<% end  %>

<%= link_to "Add a dose", new_cocktail_dose_path(@cocktail) %>
<%= link_to "Back to Homepage", cocktails_path %>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f|%>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to Homepage", cocktails_path %>

app/views/doses/new.html.erb
<h3>Dose that <%= @cocktail.name %> </h3>
<%= render 'form' %>
<%= link_to "Back to Homepage", cocktails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>